name: Run D Bot
on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  workflow_dispatch:     # manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
 
      - name: Use npm mirror
        run: npm config set registry https://registry.npmmirror.com

      - name: Install dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run D Poster Bot
        run: |
          pwd
          ls -l
          node D_Poster.js
        env:
          TWITTER_POSTER_API_KEY: ${{ secrets.TWITTER_POSTER_API_KEY }}
          TWITTER_POSTER_API_KEY_SECRET: ${{ secrets.TWITTER_POSTER_API_KEY_SECRET }}
          TWITTER_POSTER_ACCESS_TOKEN: ${{ secrets.TWITTER_POSTER_ACCESS_TOKEN }}
          TWITTER_POSTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_POSTER_ACCESS_TOKEN_SECRET }}
          NOSTR_PRIVATE_KEY: ${{ secrets.NOSTR_PRIVATE_KEY }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
